### PR TITLE
Adds upcase and downcase helpers

### PR DESCRIPTION
**Pull request by mclark4386**

### CODE REVIEW

**Comment by mclark4386** [comment]
Hopefully I didn't miss any of the bridging setup.

**Comment by markbates** [comment]
https://github.com/gobuffalo/helpers/blob/master/inflections/inflections.go They’re already mapped in inflections.

**Comment by markbates** [comment]
And by mapped I mean I never added them to the actual map. 🤦‍♂️ Would you mind fixing that?

**Comment by markbates** [comment]
I just pushed up the fix for it.

**Pull request closed without merging**
